name: Continuous Integration
run-name: CI for ${{ github.repository }}
on: [push]
jobs:
  TestAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g @expo/cli

      - name: Check Expo configuration
        run: npx expo-doctor

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Run linting (if configured)
        run: |
          if npm run lint --silent; then
            npm run lint
          else
            echo "Lint script not found, skipping..."
          fi
        continue-on-error: true

      - name: Run tests
        run: npm test -- --coverage --watchAll=false --passWithNoTests

      - name: Build JavaScript bundle (test)
        run: npx expo export --platform all --output-dir dist --clear
        env:
          EXPO_PUBLIC_SUPABASE_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_KEY }}

      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        if: success()
        with:
          file: ./coverage/lcov.info

      # ----------------------------------------------------------
      # Only run below if on main to not use up build quota limits
      # ----------------------------------------------------------
      - name: Setup EAS
        if: github.ref == 'refs/heads/main'
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build android on EAS
        if: github.ref == 'refs/heads/main'
        run: |
          eas build --platform android --profile production --non-interactive --local
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload android Build Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: "android-build.tar.gz"
